import { createClient } from '@sanity/client';

const token = process.env.SANITY_EDITOR_TOKEN;
if (!token) {
  throw new Error('SANITY_EDITOR_TOKEN is required.');
}

const projectId = process.env.SANITY_PROJECT_ID || 'd8qf2ndh';
const dataset = process.env.SANITY_DATASET || 'production';

const client = createClient({
  projectId,
  dataset,
  apiVersion: '2025-01-01',
  token,
  useCdn: false,
});

const docs = [
  {
    _id: 'service-career-guidance',
    _type: 'service',
    slug: { _type: 'slug', current: 'career-guidance' },
    order: 1,
    title: 'Career Guidance',
    description: 'Personalized career counseling to help you discover strengths, explore opportunities, and make informed decisions.',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=80',
    features: ['Psychometric Assessments', 'Career Path Planning', 'Skill Development Guidance', 'One-on-One Mentoring'],
  },
  {
    _id: 'service-workshops',
    _type: 'service',
    slug: { _type: 'slug', current: 'workshops-and-seminars' },
    order: 2,
    title: 'Workshops and Seminars',
    description: 'Interactive sessions for schools, colleges, and corporates focused on career awareness and growth.',
    imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1400&q=80',
    features: ['Student Career Programs', 'Corporate Training', 'Leadership Development', 'Parent Awareness Sessions'],
  },
  {
    _id: 'service-admission-guidance',
    _type: 'service',
    slug: { _type: 'slug', current: 'admission-guidance' },
    order: 3,
    title: 'Admission Guidance',
    description: 'Expert support for higher education choices, college selection, and admissions in India and abroad.',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1400&q=80',
    features: ['College Selection Support', 'Application Assistance', 'Course Recommendations', 'Study Abroad Guidance'],
  },
  {
    _id: 'testimonial-priya',
    _type: 'testimonial',
    slug: { _type: 'slug', current: 'priya-sharma' },
    order: 1,
    name: 'Priya Sharma',
    role: 'Class 12 Student',
    quote: 'Dr. Gladis helped me gain clarity about my career path. I now feel confident about my future.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
  },
  {
    _id: 'testimonial-rajesh',
    _type: 'testimonial',
    slug: { _type: 'slug', current: 'rajesh-kumar' },
    order: 2,
    name: 'Rajesh Kumar',
    role: 'Parent',
    quote: 'We received practical insights and a clear roadmap. The counseling process made all the difference.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
  },
  {
    _id: 'testimonial-anita',
    _type: 'testimonial',
    slug: { _type: 'slug', current: 'anita-desai' },
    order: 3,
    name: 'Anita Desai',
    role: 'Corporate Professional',
    quote: 'The transition guidance was exceptional and helped me move toward a more fulfilling career path.',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
  },
  {
    _id: 'blog-career-guide',
    _type: 'blogPost',
    slug: { _type: 'slug', current: 'choosing-the-right-career-path' },
    order: 1,
    title: 'Choosing the Right Career Path: A Guide for Students',
    excerpt: 'Align interests, skills, and values to make informed career decisions with confidence.',
    content: 'Making the right career choice starts with self-assessment, informed exploration, and structured decision-making.',
    category: 'Career Guidance',
    date: 'Jan 15, 2025',
    readTime: '5 min read',
    publishedAt: '2025-01-15T00:00:00.000Z',
  },
  {
    _id: 'blog-parents-role',
    _type: 'blogPost',
    slug: { _type: 'slug', current: 'role-of-parents-in-career-planning' },
    order: 2,
    title: 'The Role of Parents in Career Planning',
    excerpt: 'How parents can support children effectively without adding pressure.',
    content: 'Parents are most effective when they guide with empathy, provide resources, and avoid imposing expectations.',
    category: 'Parenting',
    date: 'Jan 10, 2025',
    readTime: '4 min read',
    publishedAt: '2025-01-10T00:00:00.000Z',
  },
  {
    _id: 'blog-career-transitions',
    _type: 'blogPost',
    slug: { _type: 'slug', current: 'career-transitions-with-confidence' },
    order: 3,
    title: 'Career Transitions: Navigating Change with Confidence',
    excerpt: 'Practical strategies for successful career transitions and growth.',
    content: 'Career transitions become manageable with planning, transferable-skill mapping, and a strong support system.',
    category: 'Professional Development',
    date: 'Jan 5, 2025',
    readTime: '6 min read',
    publishedAt: '2025-01-05T00:00:00.000Z',
  },
  {
    _id: 'pkg-1',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'discover-8-9' },
    order: 1,
    label: 'Discover',
    subgroup: '8-9 Students',
    amountLabel: 'Rs. 5,500',
    paymentButtonId: 'pl_RwDuOx96VYrsyN',
    features: ['Psychometric assessment', '1 career counselling session', 'Lifetime Knowledge Gateway access', 'Live webinar invites'],
  },
  {
    _id: 'pkg-2',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'discover-plus-8-9' },
    order: 2,
    label: 'Discover Plus+',
    subgroup: '8-9 Students',
    amountLabel: 'Rs. 15,000',
    paymentButtonId: 'pl_RwDq8XpK76OhB3',
    features: ['Psychometric assessments', '8 career counselling sessions (1/year)', 'Custom reports and study abroad guidance', 'CV building'],
  },
  {
    _id: 'pkg-3',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'achieve-online-10-12' },
    order: 3,
    label: 'Achieve Online',
    subgroup: '10-12 Students',
    amountLabel: 'Rs. 5,999',
    paymentButtonId: 'pl_RwDxvLPQP7j4rG',
    features: ['Psychometric assessment', '1 career counselling session', 'Lifetime Knowledge Gateway access', 'Pre-recorded webinars'],
  },
  {
    _id: 'pkg-4',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'achieve-plus-10-12' },
    order: 4,
    label: 'Achieve Plus+',
    subgroup: '10-12 Students',
    amountLabel: 'Rs. 10,599',
    paymentButtonId: 'pl_RwDzfVkQYEdAIf',
    features: ['Psychometric assessment', '4 career counselling sessions', 'Custom reports and study abroad guidance', 'CV reviews'],
  },
  {
    _id: 'pkg-5',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'ascend-online-graduates' },
    order: 5,
    label: 'Ascend Online',
    subgroup: 'Graduates',
    amountLabel: 'Rs. 6,499',
    paymentButtonId: 'pl_RwE1evNHrHWJDW',
    features: ['Psychometric assessment', '1 career counselling session', 'Lifetime Knowledge Gateway access', 'Pre-recorded webinars'],
  },
  {
    _id: 'pkg-6',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'ascend-plus-graduates' },
    order: 6,
    label: 'Ascend Plus+',
    subgroup: 'Graduates',
    amountLabel: 'Rs. 10,599',
    paymentButtonId: 'pl_RwE3WEILWB9WeJ',
    features: ['Psychometric assessment', '3 career counselling sessions', 'Certificate and online course info', 'CV reviews for jobs'],
  },
  {
    _id: 'mp-3',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'ascend-online-working-professionals' },
    order: 7,
    label: 'Ascend Online',
    subgroup: 'Working Professionals',
    amountLabel: 'Rs. 6,499',
    paymentButtonId: 'pl_RwE1evNHrHWJDW',
    features: ['Psychometric assessment', '1 career counselling session', 'Lifetime Knowledge Gateway access', 'Pre-recorded webinars'],
  },
  {
    _id: 'mp-2',
    _type: 'paymentPlan',
    slug: { _type: 'slug', current: 'ascend-plus-working-professionals' },
    order: 8,
    label: 'Ascend Plus+',
    subgroup: 'Working Professionals',
    amountLabel: 'Rs. 10,599',
    paymentButtonId: 'pl_RwE3WEILWB9WeJ',
    features: ['Psychometric assessment', '3 career counselling sessions', 'Certificate and online course info', 'CV reviews for jobs'],
  },
  {
    _id: 'career-report',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'career-report' },
    order: 1,
    label: 'Career Report',
    amountLabel: 'Rs. 1,500',
    description: 'Get a detailed report of your psychometric assessment for scientific analysis of your interests and potential future paths.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'career-report-counselling',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'career-report-counselling' },
    order: 2,
    label: 'Career Report + Career Counselling',
    amountLabel: 'Rs. 3,000',
    description: 'Connect with top career coaches to analyse your psychometric report and shortlist three career paths you are likely to enjoy and excel at.',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'knowledge-gateway',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'knowledge-gateway-career-helpline' },
    order: 3,
    label: 'Knowledge Gateway + Career Helpline Access',
    amountLabel: 'Rs. 100',
    description: 'Unlock career path information and direct access to experts via a dedicated career helpline until you land a job you love.',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'one-to-one-session',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'one-to-one-session-career-expert' },
    order: 4,
    label: 'One-to-One Session with a Career Expert',
    amountLabel: 'Rs. 3,500',
    description: 'Resolve your career queries and get future-world insights through a one-to-one session with an expert from your chosen field.',
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'college-admission-planning',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'college-admission-planning' },
    order: 5,
    label: 'College Admission Planning',
    amountLabel: 'Rs. 3,000',
    description: 'Get unbiased recommendations and details on your future college options in India and abroad in one resourceful planner.',
    imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'exam-stress-management',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'exam-stress-management' },
    order: 6,
    label: 'Exam Stress Management',
    amountLabel: 'Rs. 1,000',
    description: 'Get expert guidance on tackling exam stress, planning study schedules, revision tips, and more from top educators.',
    imageUrl: 'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=1200&q=80',
  },
  {
    _id: 'cap-100',
    _type: 'customPlan',
    slug: { _type: 'slug', current: 'cap-100' },
    order: 7,
    label: 'College Admissions Planner - 100 (CAP-100)',
    amountLabel: 'Rs. 199',
    description: 'Get an expert-curated ranked list of top 100 colleges based on verified cut-offs: Indian Ivy League, Target, Smart Backup, and Safe Bet.',
    imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
  },
];

for (const doc of docs) {
  await client.createOrReplace(doc);
}

const keepPlanIds = docs.filter((doc) => doc._type === 'paymentPlan' || doc._type === 'customPlan').map((doc) => doc._id);
const existingPlanIds = await client.fetch(`*[_type in ["paymentPlan", "customPlan"]]._id`);
for (const id of existingPlanIds) {
  if (!keepPlanIds.includes(id)) {
    await client.delete(id);
  }
}

console.log(`Seeded ${docs.length} documents in ${projectId}/${dataset}.`);

